eshop/eshop/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.contrib import admin
from django.urls import path, include

from products.views import *
from .views import home_page


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page, name = "home"),
    path('products/',include('products.urls'), name = 'products'),
    path('search/',include('search.urls'),name = 'search'),
] 
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/products/urls.py
from django.urls import path

from .views import *

app_name = "products"

urlpatterns = [
    path('',ProductListView.as_view(), name = "products"),
    path('fbv/',product_list_view, name = "products-fbv"),
    path('<int:pk>/',ProductDetailView.as_view(), name = "detail"),
] 

eshop/search/urls.py
from django.urls import path

from .views import *

app_name = "search"

urlpatterns = [
    path('',SearchProductView.as_view(), name = "search"),
]  

eshop/products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
	title = models.CharField(max_length = 120)
	description = models.TextField()
	price = models.DecimalField(decimal_places = 6, max_digits=16,default = 0.0)
	image = models.ImageField(upload_to="products/", null = True, blank = True)

	def __str__(self):
		return self.title

eshop/search/models.py
from django.db import models

# Create your models here.

eshop/eshop/views.py
from django.shortcuts import render

def home_page(request):
    context = {
        "title":"Welcome to our brand new",
        "content":"Best E-Store to buy goods.",

    }
    return render(request, "home_page.html", context)

eshop/products/views.py
from django.views.generic import ListView,DetailView
from django.shortcuts import render
from django.utils import timezone
# Create your views here.
from .models import Product

class ProductListView(ListView):
	queryset = Product.objects.all()
	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		print(context)
		return context


def product_list_view(request):
	queryset = Product.objects.all()
	context = {
		'object_list': queryset
	}
	return render(request,'products/product_list.html',context)

class ProductDetailView(DetailView):
	model = Product
	

# class ProductDetailView(DetailView):
# 	model = Product
# 	def setup(self,request,*args,**kwargs):
# 		print(args)
# 		print(kwargs)
# 		kwargs['pk'] = kwargs['id']
# 		del kwargs['id']
# 		return super().setup(request,*args,**kwargs)

		

eshop/search/views.py
from django.shortcuts import render
from django.views.generic import ListView
from products.models import Product
# Create your views here.
class SearchProductView(ListView):
	template_name = "search/search_list.html"
	def get_queryset(self, *args, **kwargs):
		request = self.request
		method_dict = request.GET
		query = method_dict.get('q',None)
		if query is not None:
			return Product.objects.filter(title__icontains=query)
		return Product.objects.all()

eshop/products/templates/products/product_detail.html
{% extends "home_page.html" %}
{% block content %}

	<style type="text/css">
		img{
		height: auto;
		max-height: 300px;
		max-width:400px;
	}
	</style>
<div class = "container">
	<div class = "row">
		<div class = "col-8 ml-auto mr-auto">
			<img src="{{product.image.url}}">
			<div>{{ product.title}}</div>
			<div>{{ product.description}}</div>
			<div>{{ product.price}}</div>
			<div>{{ now| date}}</div>
		</div>
	</div>
</div>
{% endblock %}

eshop/products/templates/products/product_list.html
{% extends "home_page.html" %}
{% block content %}
	<div>Product List:</div>
	{% for product in object_list%}
		<div><a href="{% url 'products:detail' product.pk %}">{{ product.title}}</a></div>
	{% endfor %}
{% endblock %}

eshop/search/templates/search/search_list.html
{% extends "home_page.html" %}
{% block content %}
<div class = "container">
	{% if request.GET.q %}
		<div>Search results for <strong><em>"{{request.GET.q}}"</em></strong></div>
	{% else %}
			<div class = "row">
				<div class = "col">
					<form method = "GET" id="search_form">
						<input type="text" placeholder = "Search" name="q" autocomplete="off">
					</form>
				</div>
				<div class = "col-7">
					<button type = "submit" form = "search_form" value="Submit">Submit</button>
				</div>
			</div>
		<div>Product List:</div>
	{% endif %}
	{% for product in object_list%}
		<div><a href="{% url 'products:detail' product.pk %}">{{ product.title}}</a></div>
	{% endfor %}
</div>
{% endblock %}

eshop/templates/home_page.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      
      <link rel='stylesheet' href='{% static "css/main.css" %}' >
    </head>
    <body>
      <div class='text-center'>
          <h1>{{ title }}</h1>
          <h1><a href="{% url 'home' %}">E-Shop</a></h1>
          <hr>
          <a href="{% url 'products:products' %}">Products</a>
          <a href="{% url 'search:search' %}">Search</a>
          <hr>
      </div>
      <div class='container'>
      {% block content %}
        <div class='row'>
          <div class='col'>
              <img src="{% static 'img/image.jpg' %}" class='img-fluid' />
              <p>{{ content }}</p>
          </div>
        </div>
        <!-- {% if request.user.is_authenticated %}
        <div class='row'>
          <div class='col'>
          <h1>Premium</h1>
          {{ premium_content }}
          </div>
        </div>
        {% endif %} -->
      {% endblock content %}
      </div>
    </body>
  </html>